// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaD4MwP0PQCnfuoCJzYG9aFJKDdrRGejA',
    appId: '1:674663592285:android:d10deac5230fee6645f8b4',
    messagingSenderId: '674663592285',
    projectId: 'fitsetgo-5b5d4',
    storageBucket: 'fitsetgo-5b5d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTtSu14lZ6LSVGXXAgvgnmDCozzUa78YM',
    appId: '1:674663592285:ios:59067b7e3122b82b45f8b4',
    messagingSenderId: '674663592285',
    projectId: 'fitsetgo-5b5d4',
    storageBucket: 'fitsetgo-5b5d4.appspot.com',
    androidClientId: '674663592285-2cvh28ng43t8ml5hgk8tk3csm9ljq287.apps.googleusercontent.com',
    iosClientId: '674663592285-te93rh21ao35cr5sots3tjrrnbjml7q8.apps.googleusercontent.com',
    iosBundleId: 'com.fitsetgo.app',
  );
}
